services:
  - type: web
    name: iot-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false

